name: A workflow for my Hello World file
on: push
#  push:
#    branches:
#    - master                  # master 브랜치에 푸시가 들어왔을 때 이 Workflow를 실행시키겠다는 의미
#    tags:
#     - v1
#    paths:
#      - 'test/*'
    
jobs:
  build:                      # build 라는 job을 명시
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: actions/checkout@v1   # action : 다른 사람들이 만들어 놓은 명령어들의 모음
     # - uses: ./action-a
     #   with:
     #     MY_NAME: "Mona"
          
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
#      - run: npm run eslint

      - run: docker build -t hyunflix/frontend .
      - run: docker save -o hyunflix-frontend.tar hyunflix/frontend
    

