name: A workflow for my Hello World file
on: 
  push:
    branches:
    - master                  # master 브랜치에 푸시가 들어왔을 때 이 Workflow를 실행시키겠다는 의미
    
jobs:
  build:                      # build 라는 job을 명시
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          
